# Generated by Django 5.0.4 on 2024-04-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_feedback_author_alter_feedback_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='author',
        ),
    ]
